apiVersion: v1
kind: ConfigMap
metadata:
  name: documents-config
data:
  documents-config.yaml: |
    englishStopwordsFile: "english_stopwords.json"
    output:
      type: 'database'
      connection: >
        host=localhost port=5432 user=postgres dbname=search password=thisoklagot
        sslmode=disable
    nats:
      url: "nats://127.0.0.1:4222"
      maxMsgs: 100
      jetstream:
        goroutineChanSize: 32
        thresholdOFF: 64
        thresholdON: 32
        consumer:
          durableName: uploadDocsConsumer
        name: uploadDocs
        subject: search.v1.import.doc
        recvChanSize: 1
        msgChunkSize: 5
        flowControlTimeoutInNs: "100000000ns"
        fetch:
          numMsgs: 2
          timeoutInSecs: 3s
    sidecarServiceAddr: '127.0.0.1:5555'
