apiVersion: apps/v1
kind: Deployment
metadata:
  labels:   # labels define key-value pairs. Each key must be unique
            # for a given object
    app: nats
  name: nats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:   # Template specifies the pod specification.
              # Each pod will be created using this template.
    metadata:
      labels:
        app: nats     # Labels given to each pod
    spec:
      containers:             # Containers in this pod
        - name: nats
          image: nats:latest
          ports:
            - containerPort: 4222 # NATS will listen to this default port for clients.
