
apiVersion: v1
kind: Service
metadata:
  name: nats
spec:
  type: ClusterIP
  selector:
   app: nats
  sessionAffinity: None   # This is the default, and means requests are
                          # sent to any provider of this service.
  ports:
  - name: nats-listen-port
    port: 4222
    targetPort: nats-port
