apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  labels:   # labels define key-value pairs. Each key must be unique
            # for a given object
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:   # Template specifies the pod specification.
              # Each pod will be created using this template.
    metadata:
      labels:
        app: postgres     # Labels given to each pod
    spec:
      # initContainers:         # Init containers finish before any other
                              # container can start.
                              # There can be many init containers.
                              # They run in the sequence given here.
                              # Each has to complete before the next is started.
                              # After the last completes, the containers are
                              # all started in parallel.
      #  - name: init-container
          # image: init-container:latest
      containers:             # Containers in this pod
        - name: postgres   # Name of the container
          image: postgres:latest
          imagePullPolicy: "IfNotPresent"
          envFrom:
            - configMapRef:
                name: postgres-config
          ports:
            - containerPort: 5432 # and this database port,
              name: postgres-port
          volumeMounts:
          - name: postgres-data
            mountPath: /var/lib/postgres/data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc
