apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: ClusterIP
  selector:
   app: postgres
  sessionAffinity: None   # This is the default, and means requests are
                          # sent to any provider of this service.
  ports:
  - name: postgres-listen-port
    port: 5432
    targetPort: postgres-port
