apiVersion: v1
kind: ConfigMap
metadata:
  name: upload-config
data:
  upload-config.yaml: |
    serviceName: "upload"
    output:
      type: database
      connection: "host=postgres port=5432 user=pg dbname=search password=pg sslmode=disable"
    sidecarServiceAddr: "127.0.0.1:5555"
