apiVersion: apps/v1
kind: Deployment
metadata:
  labels:   # labels define key-value pairs. Each key must be unique
            # for a given object
    app: upload
  name: upload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upload
  template:   # Template specifies the pod specification.
              # Each pod will be created using this template.
    metadata:
      labels:
        app: upload     # Labels given to each podspec
    spec:
        # initContainers:         # Init containers finish before any other
                                # container can start.
                                # There can be many init containers.
                                # They run in the sequence given here.
                                # Each has to complete before the next is started.
                                # After the last completes, the containers are
                                # all started in parallel.
        #  - name: init-container
            # image: init-container:latest
      containers:             # Containers in this pod
        - name: sidecar   # Name of the container
          image: sidecar:latest
          imagePullPolicy: Never
          ports:
            - name: postgres-port
              containerPort: 5432 # Listens on this database port.
                # - name: grpc-port
                # containerPort: 5555 # Listens on this GRPC port.
          volumeMounts:
          - name: mnt-config-sc
            mountPath: /mnt
            readOnly: true
        - name: upload   # Name of the container
          image: upload:latest
          imagePullPolicy: Never
          ports:
            - name: postgres-port
              containerPort: 5432 # Listens on this database port.
                # - name: grpc-port
                # containerPort: 5555 # Listens on this GRPC port.
          volumeMounts:
          - name: mnt-config-pl
            mountPath: /mnt
            readOnly: true
      volumes:
        - name: mnt-config-sc
          configMap:
            name: sidecar-config
        - name: mnt-config-pl
          configMap:
            name: upload-config
