// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// DocsColumns holds the columns for the "docs" table.
	DocsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true},
		{Name: "word_ints", Type: field.TypeBytes},
		{Name: "input_doc_id", Type: field.TypeString},
		{Name: "user_id", Type: field.TypeString},
		{Name: "business_id", Type: field.TypeString},
		{Name: "stars", Type: field.TypeFloat32},
		{Name: "useful", Type: field.TypeInt16},
		{Name: "funny", Type: field.TypeInt16},
		{Name: "cool", Type: field.TypeInt16},
		{Name: "text", Type: field.TypeString},
		{Name: "date", Type: field.TypeString},
	}
	// DocsTable holds the schema information for the "docs" table.
	DocsTable = &schema.Table{
		Name:       "docs",
		Columns:    DocsColumns,
		PrimaryKey: []*schema.Column{DocsColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		DocsTable,
		UsersTable,
	}
)

func init() {
}
