// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/samirgadkari/search/ent/doc"
)

// DocCreate is the builder for creating a Doc entity.
type DocCreate struct {
	config
	mutation *DocMutation
	hooks    []Hook
}

// SetWordInts sets the "wordInts" field.
func (dc *DocCreate) SetWordInts(b []byte) *DocCreate {
	dc.mutation.SetWordInts(b)
	return dc
}

// SetInputDocId sets the "inputDocId" field.
func (dc *DocCreate) SetInputDocId(s string) *DocCreate {
	dc.mutation.SetInputDocId(s)
	return dc
}

// SetUserId sets the "userId" field.
func (dc *DocCreate) SetUserId(s string) *DocCreate {
	dc.mutation.SetUserId(s)
	return dc
}

// SetBusinessId sets the "businessId" field.
func (dc *DocCreate) SetBusinessId(s string) *DocCreate {
	dc.mutation.SetBusinessId(s)
	return dc
}

// SetStars sets the "stars" field.
func (dc *DocCreate) SetStars(f float32) *DocCreate {
	dc.mutation.SetStars(f)
	return dc
}

// SetUseful sets the "useful" field.
func (dc *DocCreate) SetUseful(i int16) *DocCreate {
	dc.mutation.SetUseful(i)
	return dc
}

// SetFunny sets the "funny" field.
func (dc *DocCreate) SetFunny(i int16) *DocCreate {
	dc.mutation.SetFunny(i)
	return dc
}

// SetCool sets the "cool" field.
func (dc *DocCreate) SetCool(i int16) *DocCreate {
	dc.mutation.SetCool(i)
	return dc
}

// SetText sets the "text" field.
func (dc *DocCreate) SetText(s string) *DocCreate {
	dc.mutation.SetText(s)
	return dc
}

// SetDate sets the "date" field.
func (dc *DocCreate) SetDate(s string) *DocCreate {
	dc.mutation.SetDate(s)
	return dc
}

// SetID sets the "id" field.
func (dc *DocCreate) SetID(u uint32) *DocCreate {
	dc.mutation.SetID(u)
	return dc
}

// Mutation returns the DocMutation object of the builder.
func (dc *DocCreate) Mutation() *DocMutation {
	return dc.mutation
}

// Save creates the Doc in the database.
func (dc *DocCreate) Save(ctx context.Context) (*Doc, error) {
	var (
		err  error
		node *Doc
	)
	if len(dc.hooks) == 0 {
		if err = dc.check(); err != nil {
			return nil, err
		}
		node, err = dc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*DocMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = dc.check(); err != nil {
				return nil, err
			}
			dc.mutation = mutation
			if node, err = dc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(dc.hooks) - 1; i >= 0; i-- {
			if dc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = dc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, dc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (dc *DocCreate) SaveX(ctx context.Context) *Doc {
	v, err := dc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dc *DocCreate) Exec(ctx context.Context) error {
	_, err := dc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dc *DocCreate) ExecX(ctx context.Context) {
	if err := dc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (dc *DocCreate) check() error {
	if _, ok := dc.mutation.WordInts(); !ok {
		return &ValidationError{Name: "wordInts", err: errors.New(`ent: missing required field "Doc.wordInts"`)}
	}
	if _, ok := dc.mutation.InputDocId(); !ok {
		return &ValidationError{Name: "inputDocId", err: errors.New(`ent: missing required field "Doc.inputDocId"`)}
	}
	if _, ok := dc.mutation.UserId(); !ok {
		return &ValidationError{Name: "userId", err: errors.New(`ent: missing required field "Doc.userId"`)}
	}
	if _, ok := dc.mutation.BusinessId(); !ok {
		return &ValidationError{Name: "businessId", err: errors.New(`ent: missing required field "Doc.businessId"`)}
	}
	if _, ok := dc.mutation.Stars(); !ok {
		return &ValidationError{Name: "stars", err: errors.New(`ent: missing required field "Doc.stars"`)}
	}
	if _, ok := dc.mutation.Useful(); !ok {
		return &ValidationError{Name: "useful", err: errors.New(`ent: missing required field "Doc.useful"`)}
	}
	if _, ok := dc.mutation.Funny(); !ok {
		return &ValidationError{Name: "funny", err: errors.New(`ent: missing required field "Doc.funny"`)}
	}
	if _, ok := dc.mutation.Cool(); !ok {
		return &ValidationError{Name: "cool", err: errors.New(`ent: missing required field "Doc.cool"`)}
	}
	if _, ok := dc.mutation.Text(); !ok {
		return &ValidationError{Name: "text", err: errors.New(`ent: missing required field "Doc.text"`)}
	}
	if _, ok := dc.mutation.Date(); !ok {
		return &ValidationError{Name: "date", err: errors.New(`ent: missing required field "Doc.date"`)}
	}
	if v, ok := dc.mutation.ID(); ok {
		if err := doc.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Doc.id": %w`, err)}
		}
	}
	return nil
}

func (dc *DocCreate) sqlSave(ctx context.Context) (*Doc, error) {
	_node, _spec := dc.createSpec()
	if err := sqlgraph.CreateNode(ctx, dc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint32(id)
	}
	return _node, nil
}

func (dc *DocCreate) createSpec() (*Doc, *sqlgraph.CreateSpec) {
	var (
		_node = &Doc{config: dc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: doc.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint32,
				Column: doc.FieldID,
			},
		}
	)
	if id, ok := dc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := dc.mutation.WordInts(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeBytes,
			Value:  value,
			Column: doc.FieldWordInts,
		})
		_node.WordInts = value
	}
	if value, ok := dc.mutation.InputDocId(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: doc.FieldInputDocId,
		})
		_node.InputDocId = value
	}
	if value, ok := dc.mutation.UserId(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: doc.FieldUserId,
		})
		_node.UserId = value
	}
	if value, ok := dc.mutation.BusinessId(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: doc.FieldBusinessId,
		})
		_node.BusinessId = value
	}
	if value, ok := dc.mutation.Stars(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat32,
			Value:  value,
			Column: doc.FieldStars,
		})
		_node.Stars = value
	}
	if value, ok := dc.mutation.Useful(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt16,
			Value:  value,
			Column: doc.FieldUseful,
		})
		_node.Useful = value
	}
	if value, ok := dc.mutation.Funny(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt16,
			Value:  value,
			Column: doc.FieldFunny,
		})
		_node.Funny = value
	}
	if value, ok := dc.mutation.Cool(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt16,
			Value:  value,
			Column: doc.FieldCool,
		})
		_node.Cool = value
	}
	if value, ok := dc.mutation.Text(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: doc.FieldText,
		})
		_node.Text = value
	}
	if value, ok := dc.mutation.Date(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: doc.FieldDate,
		})
		_node.Date = value
	}
	return _node, _spec
}

// DocCreateBulk is the builder for creating many Doc entities in bulk.
type DocCreateBulk struct {
	config
	builders []*DocCreate
}

// Save creates the Doc entities in the database.
func (dcb *DocCreateBulk) Save(ctx context.Context) ([]*Doc, error) {
	specs := make([]*sqlgraph.CreateSpec, len(dcb.builders))
	nodes := make([]*Doc, len(dcb.builders))
	mutators := make([]Mutator, len(dcb.builders))
	for i := range dcb.builders {
		func(i int, root context.Context) {
			builder := dcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DocMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, dcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, dcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint32(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, dcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (dcb *DocCreateBulk) SaveX(ctx context.Context) []*Doc {
	v, err := dcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dcb *DocCreateBulk) Exec(ctx context.Context) error {
	_, err := dcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dcb *DocCreateBulk) ExecX(ctx context.Context) {
	if err := dcb.Exec(ctx); err != nil {
		panic(err)
	}
}
