// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/samirgadkari/search/ent/doc"
	"github.com/samirgadkari/search/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	docFields := schema.Doc{}.Fields()
	_ = docFields
	// docDescID is the schema descriptor for id field.
	docDescID := docFields[0].Descriptor()
	// doc.IDValidator is a validator for the "id" field. It is called by the builders before save.
	doc.IDValidator = docDescID.Validators[0].(func(uint32) error)
}
