// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Doc is the predicate function for doc builders.
type Doc func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
